-- Extend OrderStatus enum with additional distinct values for Romanian UI labels
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'SUPPLIER_OUT_OF_STOCK';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'UNPAID_ORDER';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PAID_FULL_ORDER';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PAID_PARTIAL_ORDER';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'IN_DELIVERY';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'RETURNED_REFUSED';
