// Romanian localization for MaterialReactTable
export const tableLocalization = {
  actions: 'Acțiuni',
  and: 'și',
  cancel: 'Anulează',
  changeFilterMode: 'Schimbă modul de filtrare',
  changeSearchMode: 'Schimbă modul de căutare',
  clearFilter: 'Șterge filtrul',
  clearSearch: 'Șterge căutarea',
  clearSort: 'Șterge sortarea',
  clickToCopy: 'Click pentru a copia',
  collapse: 'Restrânge',
  collapseAll: 'Restrânge toate',
  columnActions: 'Acțiuni coloană',
  copiedToClipboard: 'Copiat în clipboard',
  dropToGroupBy: 'Trage aici pentru a grupa după {column}',
  edit: 'Editează',
  expand: 'Extinde',
  expandAll: 'Extinde toate',
  filterArrIncludes: 'Include',
  filterArrIncludesAll: 'Include toate',
  filterArrIncludesSome: 'Include unele',
  filterBetween: 'Între',
  filterBetweenInclusive: 'Între (inclusiv)',
  filterByColumn: 'Filtrează după {column}',
  filterContains: 'Conține',
  filterEmpty: 'Gol',
  filterEndsWith: 'Se termină cu',
  filterEquals: 'Egal',
  filterEqualsString: 'Egal',
  filterFuzzy: 'Căutare fuzzy',
  filterGreaterThan: 'Mai mare decât',
  filterGreaterThanOrEqualTo: 'Mai mare sau egal cu',
  filterInNumberRange: 'În intervalul numeric',
  filterIncludesString: 'Include',
  filterIncludesStringSensitive: 'Include (sensibil)',
  filterLessThan: 'Mai mic decât',
  filterLessThanOrEqualTo: 'Mai mic sau egal cu',
  filterMode: 'Mod filtrare: {filterType}',
  filterNotEmpty: 'Nu este gol',
  filterNotEquals: 'Nu este egal',
  filterStartsWith: 'Începe cu',
  filterWeakEquals: 'Egal',
  filteringByColumn: 'Filtrare după {column} - {filterType}: {filterValue}',
  goToFirstPage: 'Mergi la prima pagină',
  goToLastPage: 'Mergi la ultima pagină',
  goToNextPage: 'Mergi la pagina următoare',
  goToPreviousPage: 'Mergi la pagina anterioară',
  grab: 'Apucă',
  groupByColumn: 'Grupează după {column}',
  groupedBy: 'Grupat după ',
  hideAll: 'Ascunde toate',
  hideColumn: 'Ascunde coloana {column}',
  max: 'Max',
  min: 'Min',
  move: 'Mută',
  noRecordsToDisplay: 'Nu există înregistrări de afișat',
  noResultsFound: 'Nu au fost găsite rezultate',
  of: 'din',
  or: 'sau',
  pinToLeft: 'Fixează la stânga',
  pinToRight: 'Fixează la dreapta',
  resetColumnSize: 'Resetează dimensiunea coloanei',
  resetOrder: 'Resetează ordinea',
  rowActions: 'Acțiuni rând',
  rowNumber: '#',
  rowNumbers: 'Numere rânduri',
  rowsPerPage: 'Rânduri pe pagină',
  save: 'Salvează',
  search: 'Caută',
  select: 'Selectează',
  selectedCountOfRowCountRowsSelected: '{selectedCount} din {rowCount} rând(uri) selectat(e)',
  showAll: 'Afișează toate',
  showAllColumns: 'Afișează toate coloanele',
  showHideColumns: 'Afișează/Ascunde coloane',
  showHideFilters: 'Afișează/Ascunde filtre',
  showHideSearch: 'Afișează/Ascunde căutare',
  sortByColumnAsc: 'Sortează {column} crescător',
  sortByColumnDesc: 'Sortează {column} descrescător',
  sortedByColumnAsc: 'Sortat după {column} crescător',
  sortedByColumnDesc: 'Sortat după {column} descrescător',
  thenBy: ', apoi după ',
  toggleDensity: 'Comută densitatea',
  toggleFullScreen: 'Comută ecran complet',
  toggleSelectAll: 'Comută selectare totală',
  toggleSelectRow: 'Comută selectare rând',
  toggleVisibility: 'Comută vizibilitatea',
  // Density options
  compact: 'Compact',
  comfortable: 'Confortabil', 
  spacious: 'Spațios',
  ungroupByColumn: 'Degrupează după {column}',
  unpin: 'Desprinde',
  unpinAll: 'Desprinde toate',
  unsorted: 'Nesortat',
};
